// <auto-generated />
using ApiPassagem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPassagem.Migrations
{
    [DbContext(typeof(APIDbContext))]
    partial class APIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiPassagem.Models.Passagem", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("chegada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("partida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("passageiros")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("codigo");

                    b.ToTable("Passagem");
                });
#pragma warning restore 612, 618
        }
    }
}
